best_hyperparameters:
  batch_size: 64
  conv_channels: 8
  dropout: 0.4699211392772475
  end_channels: 8
  gcn_depth: 4
  layers: 4.0
  learning_rate: 0.006813387761851225
  node_dim: 21.0
  residual_channels: 16
  skip_channels: 8
  subgraph_size: 22.0
  weight_decay: 7.490814196537802e-05
best_objective_value: 0.009623028648396334
test|horizon:
  MAE-mean: '0.012'
  MAPE-mean: 8.346%
  R2-mean: '-1.077'
  RMSE-mean: '0.022'
  RMSPE-mean: 17.361%
